wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.18.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_acc_step
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    - 1: val_error
      5: 1
      6:
      - 1
    - 1: train_acc_epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    python_version: 3.9.7
    start_time: 1648404151
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      3:
      - 7
      - 17
      4: 3.9.7
      5: 0.12.11
      6: 4.18.0.dev0
      8:
      - 2
      - 5
